const wordBank = [
	"ABLIN","ABDOX","ADNAL","AKIVA","APRUT","ASDER","BABON","BERMO","BIVDI","BOFUM","DETAX","IRKUM","ADSIS","ARVOK","BAPDA","BATED","DODIG","EIDER","EKREN","ELBON","ENDEQ","EPOXI","EPIDU","ERUDA","ERVAD","GANET","GARTI","GIRAS","GOSEL","INTOP","IRDEX","KANUS","KEPOR","KERAV","KOGAX","KUDOM","LIPGO","MAXEV","NASRI","NEKIL","NEPOD","NITIL","ORVEN","OSLEX","OTNER","PEKOK","RISAP","ROKNA","RONON","RUBAR","SIVNA","SUTEX","SORIN","SUGAD","UGNOR","UMDAR","LUTIP","ABAGU","ABBAL","ABDUK","ABGEP","ABIDO","ADARA","ADVAT","ADARU","ADBUS","ADMUP","AGINI","AGORI","AKIGO","ALAVA","ALUTA","AMDEP","AMDIL","AMELI","AMPIT","ARDAM","ARKIL","ASGON","ASKUP","ATLAM","ATSUR","AMLAD","APSOV","BABAN","BABRA","BADEN","BADSI","BAFBI","BAGIT","BAGSO","BAKBA","BAKOT","BAKOX","BAKUR","BALNA","BAMLI","BANBA","BAPGO","BARNU","BAVUD","BEDRA","BEGAS","BEGID","BEPAN","BERUX","BEVES","BEXET","BIBLA","BILTO","BIMGO","BOKLI","BOYNE","BUNED","BUNON","DEGOS","DEMOT","DERAG","DEROX","DESUB","DEVOL","DEXEN","DIGAN","DIGID","DIMGO","DIMLI","DIMUS","DINIL","DINIM","DIRUM","DISUR","DOGAL","DOKEK","DOLIP","DOLOP","DONAX","DONEB","DONIB","DONOX","DUNLO","EBABO","EDONO","EIDER","ELKAM","ELPOM","EKNIS","ELSOX","ELTIG","EMPER","ENOKU","ENULA","EPERO","EPUNA","EPVIN","ERABI","ERNAN","ERTER","ESATA","ETARI","EVBAK","EVRIN","FERAH","FURCA","GAKBO","GAMDO","GAPLI","GATLO","GATRA","GERVO","GELPO","GILAN","GILOG","GIMRO","GINGA","GINGI","GINIS","GIPER","GISTI","GIVOL","GOKLI","GOTNA","GOMUP","GONAN","GORTO","GOSDA","GOTEM","GULTU","GUNSO","GURGA","GIGTO","HOUSE","HESRA","IBATU","IBROD","IDBAN","IDEXA","INDAP","INKUR","INPAT","INRAD","INSAL","JABEX","KEKEG","KEKUL","KELOL","KENOL","KEREX","KESIX","KETAG","KISHA","KOGAD","KOKIB","KOMAG","KOMAL","KOMER","KONAP","KOPAX","KOPES","KORAK","KOTEX","KUDAG","KUGUR","KURUM","LANRO","LANVA","LAPMO","LAREM","LARLA","LASMO","LASNO","LAZBE","LEDGO","LEKVA","LELDO","LEMGU","LEMTA","LESLU","LESRO","LIFFY","LILNO","LIMRI","LINRA","LOBGO","LODLA","LOMVO","LONDU","LORKO","LORLA","LULOX","LUTOV","LUNIG","LUPOR","LUSAT","LUTIP","LUVIS","LYNAS","MAGIT","MALAX","MALOT","MALUD","MAPAG","MAPOT","MARNO","MAZAN","MELIK","MERLY","MIMKU","MOGLO","MOLAK","MOMIN","MOPAT","MOPOM","MORAG","MULLA","NASBA","NATKO","NAVEM","NEBIN","NEGEL","NEKAD","NEMAK","NENAG","NEPOG","NEMAK","NERTU","NESOL","NESON","NETKI","NEVRI","NEXAT","NIBOG","NILAV","NIMAT","NIPIT","NONSI","NORLA","NOSLO","NUPVO","ODANU","ODLUM","OFCER","OFMOF","OGDUM","OGONO","OGTUG","OLAPO","OLGON","OLONO","OMOKO","ORTOM","OSBOX","OSGAR","PABMO","PELIG","PEMOB","PENIL","PERIL","PESIT","PEVAN","PHILI","PIGET","PIKIL","RAKUM","RAMOX","RATKA","RERKA","RESNO","REVNU","RIKUL","RILED","RIMVU","RINGI","RINUS","RITIS","ROBVO","RODEL","ROLEX","RONAN","ROPED","ROSRO","ROTEV","ROTSO","ROVAL","RULAV","RUTOK","RUXIN","SAMON","SITKO","SITKU","SLANY","SMILO","SOMAX","SOMBO","SOPAX","SOVED","SOVIX","SUNOT","SUROX","SUTEX","SUVAN","TADEX","TAKAS","TAMEL","TEDVO","TERDU","TIDGO","TIGPA","TIMRA","TIPMO","TIPUR","TIRUK","TISMO","TOBOR","TOBRI","TOGBO","TOMTO","TOPDA","TORLU","TUGSI","TULSO","TULTA","TURLU","TUVEN","ULSIT","ULTAG","UMLER","UNBEG","UNLID","UPLOM","UPLON","UNDUX","VAPAL","VATRY","VENER","XETBO"
]

let word

let grid

let letterW = 75
let letterH = 75

let gameState="PLAYING"

function setup() {
	createCanvas(windowWidth, windowHeight);
	background(100);
	
	//Choose the word
	word = chooseRandomWord()
	// word="CODES"
	console.log(word)
	
	//Create the grid
	grid = new Grid()
}

function chooseRandomWord() {
	return random(wordBank)
}

function keyPressed() {
	if(keyCode===ENTER) {grid.changeCurrentRow()}
	else if(keyCode==BACKSPACE) {grid.rows[grid.currentRowIdx].backspace()}
	else {
		grid.rows[grid.currentRowIdx].changeLetter(key)
	}
}

function draw() {
	background(12,12,13)
	
	if(gameState=="PLAYING") {
		//Title text
		push()
		fill(255,255,255)
		textSize(50)
		textAlign(CENTER)
		text("Wordle", windowWidth/2, 70)
		pop()

		grid.draw()
	}
	
	if(gameState=="END") {
		push()
		fill(255,255,255)
		textSize(50)
		textAlign(CENTER)
		text("Correct!", windowWidth/2, 70)
		text("The word was "+word+"!", windowWidth/2, 130)
		text("The word was "+word+"!", windowWidth/2, 130)
		pop()
	}
}